apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: alms
  name: identity-linear-memory-stress
spec:
  entry: entry
  templates:
  - name: entry
    templateType: Serial
    deadline: 2h30m
    children:
    - suspending1
    - 80mb-mem
    - 82mb-mem
    - 84mb-mem
    - 86mb-mem
    - 88mb-mem
    - 90mb-mem
    - 92mb-mem
    - 94mb-mem
    - 96mb-mem
    - 98mb-mem
    - 100mb-mem
    - 102mb-mem
  - name: suspending1
    templateType: Suspend
    deadline: 30m
  - name: 80mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 80MB
          time: 10m
          oomScoreAdj: -1000
  - name: 82mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 82MB
          time: 10m
          oomScoreAdj: -1000
  - name: 84mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 84MB
          time: 10m
          oomScoreAdj: -1000
  - name: 86mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 86MB
          time: 10m
          oomScoreAdj: -1000
  - name: 88mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 88MB
          time: 10m
          oomScoreAdj: -1000
  - name: 90mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 90MB
          time: 10m
          oomScoreAdj: -1000
  - name: 92mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 92MB
          time: 10m
          oomScoreAdj: -1000
  - name: 94mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 94MB
          time: 10m
          oomScoreAdj: -1000
  - name: 96mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 96MB
          time: 10m
          oomScoreAdj: -1000
  - name: 98mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 98MB
          time: 10m
          oomScoreAdj: -1000
  - name: 100mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 100MB
          time: 10m
          oomScoreAdj: -1000
  - name: 102mb-mem
    templateType: StressChaos
    deadline: 10m
    stressChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identity
        podPhaseSelectors:
        - Running
      mode: all
      stressors:
        memory:
          workers: 3
          size: 102MB
          time: 10m
          oomScoreAdj: -1000
