apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: alms
  name: linear-network-delay-identityapi
spec:
  entry: entry
  templates:
  - name: entry
    templateType: Serial
    deadline: 2h30m
    children:
    - suspending1
    - 1000ms-delay
    - 1500ms-delay
    - 2000ms-delay
    - 2500ms-delay
    - 3000ms-delay
    - 3500ms-delay
    - 4000ms-delay
    - 4500ms-delay
    - 5000ms-delay
    - 5000ms-delay
    - 5000ms-delay
    - 5000ms-delay
  - name: suspending1
    templateType: Suspend
    deadline: 30m
  - name: 1000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 1000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 1500ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 1500ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 2000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 2000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 2500ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 2500ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 3000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 3000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 3500ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 3500ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 4000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 4000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 4500ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 4500ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 5000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 5000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 5000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 5000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 5000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 5000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 5000ms-delay
    templateType: NetworkChaos
    deadline: 10m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: identityapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 5000ms
        correlation: '0'
        jitter: 0ms
      direction: both
      target:
        selector:
          namespaces:
          - alms
        mode: all
