apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: alms
  name: userapi-linear-network-delay
spec:
  entry: entry
  templates:
  - name: entry
    templateType: Serial
    deadline: 3h10m
    children:
    - suspending1
    - 50ms-delay
    - 100ms-delay
    - 150ms-delay
    - 200ms-delay
    - 250ms-delay
    - 300ms-delay
    - 350ms-delay
    - 400ms-delay
    - 450ms-delay
    - 500ms-delay
  - name: suspending1
    templateType: Suspend
    deadline: 10m
  - name: 50ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 50ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 100ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 100ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 150ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 150ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 200ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 200ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 250ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 250ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 300ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 300ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 350ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 350ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 400ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 400ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 450ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 450ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 500ms-delay
    templateType: NetworkChaos
    deadline: 18m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: delay
      delay:
        latency: 500ms
        correlation: '0'
        jitter: 0ms
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
