apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  namespace: alms
  name: userapi-constant-network-loss
spec:
  entry: entry
  templates:
  - name: entry
    templateType: Serial
    deadline: 2h30m
    children:
    - suspending1
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
    - 50-loss
  - name: suspending1
    templateType: Suspend
    deadline: 30m
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
  - name: 50-loss
    templateType: NetworkChaos
    deadline: 5m
    networkChaos:
      selector:
        namespaces:
        - alms
        labelSelectors:
          app.kubernetes.io/name: userapi
        podPhaseSelectors:
        - Running
      mode: all
      action: loss
      loss:
        loss: '50'
        correlation: '0'
      direction: to
      target:
        selector:
          namespaces:
          - alms
        mode: all
